### ISSUE TITLE
BOM as markdown

### ISSUE THREAD

**Issue by KarlZeilhofer** [cskozlowski/mmu2#1]
Dear Chuk, 

I've reformatted your BOM, to be a markdown file and added the link to this github repo:

Here is the code:
```
DIY Prusa Multi Material Upgrade (MMU) 2.0
==========================================
Bill of Materials (10.7.2018)
------------------------------
For firmware, please refer to https://github.com/cskozlowski/mmu2

Be warned, this is a very difficult project. 
Everyone wants to know the $$$, the list below is under $200 (US). 
The most expensive parts are:  stepper motors ($30 for the three I purchased), arduino ($14) and RAMPS 1.6 board ($14).
This is a starter list of stuff you will need to complete this MMU2 home brew clone

# Change Notes:
* 10.17.18 Added 3 STL files required for build of the home-brew MMU2 (do the NEMA17 holder in PETG, other pieces can be 
                                                                          done in PLA or PETG)
* 10.16.18 Changed the stepper motor recommendation, you can also get them on aliexpress.com)
* 10.10.18  Added references to 3 STL design files that you will need (see STL for additional details)
* 10.9.18   626-ZZ should say 625-ZZ bearings ... 626-ZZ are rarer than 1.85mm PTFE
* 10.9.18   Added 7mm ball bearing (you need this for the FINDA detector)
* 10.9.18   Added 5mm x 8mm coupler (need this for the selector stepper motor to threaded rod)

# BOM

## Prusa Parts
* MMU2 plastic parts - https://www.prusa3d.com/prusa-i3-printable-parts/

## Motors

* 3 Stepper Motors
  (DO NOT PURCHASE THESE MOTORS, THEY DO NOT HAVE SUFFICIENT STALL TORQUE)(https://www.amazon.com/gp/product/B0716S32G4/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1)
            (these motors are super cheap $10 per motor ... don't buy them because they don't have sufficient torque)
            (I used them for 3 weeks and chased problems that won't be there if you get better motors
            (get the motors I list below)
            
            
* 3   Stepper Motors 
  (PURCHASE THESE STEPPER MOTORS INSTEAD)(https://www.amazon.com/gp/product/B06XSYP24P/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)

  (these motors have 46 N-cm of stall torque.  They idler stepper motor needs quite a bit of stall torque to stay
            in place when the bearing is being moved against the extruder stepper motor).
            
  Get a motor with a minimum of 45 N-cm of stall torque (you will thank me later)
         
    These motors are nice and cheap - the problem with cheap is they are not 100% reliable. I am testing another brand at the 
    moment and when I have some decent test results I will report back.

## Other Stuff
* 5   mk8 hobbed gears (https://www.amazon.com/gp/product/B07CJPP7R7/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1)
* 2   100mm x 5mm steel shafts (https://www.amazon.com/gp/product/B01B27MJC6/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1)
     (these shafts are used to make your 16mm spindles for the bearings,  you can also order 16mm x 5mm spindles from McMcaster-Carr,
     (however, they are wicked tight on the bearings)
* 2   150mm x 5mm steel shafts (https://www.amazon.com/gp/product/B01B5QTM8I/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)
      (these shafts are used for the selector head shaft guides, you will have to cut them down to size)
      (if you don't know how to cut steel shafts then please stop and go do something else)
* 9   625-ZZ bearings (https://www.amazon.com/gp/product/B01CUTIQWW/ref=oh_aui_detailpage_o04_s01?ie=UTF8&psc=1)
* 20  3mm thin (1.8mm) square nuts) https://www.amazon.com/gp/product/B073SBCMBM/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1
* 1   5mm x 5mm coupler https://www.amazon.com/gp/product/B0159WO7T8/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1
                     (you need one but buy two because you can) 
* 1   5mm x 8mm coupler  (amazon.com ... too lazy to provide the link at the moment).
* 25' 4mm OD x 2mm ID PTFE Tubing (https://www.amazon.com/gp/product/B073RFQQ3Z/ref=oh_aui_detailpage_o09_s00?ie=UTF8&th=1)
                     Needed for the feeders from the spools to the MMU2 unit, you will learn to hate PTFE tubing
* 1   50mm 4mm OD x 1.85mm ID PTFE Tubing (flurostore.com has 1.80mm ID tubing - it works !!!)
                By far the most difficult part to obtain, it should just be called unobtanium
* 1   150mm x 8mm threaded shaft (https://www.amazon.com/gp/product/B07C8P1DWX/ref=oh_aui_detailpage_o08_s01?ie=UTF8&psc=1)
                (yes, you will have to cut it to size using some of your cool shop tools)
* 10  PC4-10 PTFE connectors (https://www.amazon.com/gp/product/B01IB81IHG/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1)
                (get these, they are awesome)
* 1   12-15V, 2A  Power supply - needed for the Arduino Mega/RAMPS board for initial testing
* 1   Arduino Mega 2560 (https://www.amazon.com/gp/product/B01H4ZDYCE/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)
* 1   1.x RAMPS Boards (https://www.amazon.com/gp/product/B0794YN8XK/ref=oh_aui_detailpage_o09_s00?ie=UTF8&psc=1)
                    (home for all of your stepper motor controllers)
* 3  8825 Stepper Motor Controller (https://www.amazon.com/gp/product/B00S3Q9YZA/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1)
                    (make certain to tweak the voltage rheostat on the top of this little wonder, goto polulu website)
                    (I currently have mine set to 0.60V - don't go too high you will fry this component)
* 1  Razor Blades (https://www.amazon.com/gp/product/B007QYAJRC/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1)
* 1  microswitch   (https://www.amazon.com/gp/product/B06XSBYQ8H/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1)
* 1  FINDA (aka PINDA) Probe (https://www.amazon.com/URBEST-Detecting-Distance-Inductive-Proximity/dp/B01M1777XK/ref=sr_1_fkmr1_3?s=industrial&ie=UTF8&qid=1538915473&sr=1-3-fkmr1&keywords=prusa+pinda+probe)
                  ( I had a spare probe laying around so I have NOT tried this inductive probe)
                  (they are also available from aliexpress.com)
* 1  7mm ball bearing  (mcmaster.carr or amazon), you only need one but you will have to buy many more

## Custom STL Files
* 1  MMU2 to PTFE Festo Coupler 
* 1  MK3 to PTFE Festo Coupler (w/ microswitch holder)
* 1  Selector Motor Mount offset block

## DigiKey Components (needed for cables and wiring)
(to be completed)

      


## Random Tools
(it's a project, you've got to buy new tools - you live for this stuff)
* 1 Reamer (https://www.amazon.com/gp/product/B01EIH573K/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1)
           (used to make awesome interior bevelled edges in that damn 2mm (and 1.80mm) PTFE
* 50mm cutting jig (https://www.thingiverse.com/thing:3062809)    
           (oh look, you get to make something with your 3d printer)
           
```

And here how it would be rendered in github:
----

DIY Prusa Multi Material Upgrade (MMU) 2.0
==========================================
Bill of Materials (10.7.2018)
------------------------------
For firmware, please refer to https://github.com/cskozlowski/mmu2

Be warned, this is a very difficult project. 
Everyone wants to know the $$$, the list below is under $200 (US). 
The most expensive parts are:  stepper motors ($30 for the three I purchased), arduino ($14) and RAMPS 1.6 board ($14).
This is a starter list of stuff you will need to complete this MMU2 home brew clone

# Change Notes:
* 10.17.18 Added 3 STL files required for build of the home-brew MMU2 (do the NEMA17 holder in PETG, other pieces can be 
                                                                          done in PLA or PETG)
* 10.16.18 Changed the stepper motor recommendation, you can also get them on aliexpress.com)
* 10.10.18  Added references to 3 STL design files that you will need (see STL for additional details)
* 10.9.18   626-ZZ should say 625-ZZ bearings ... 626-ZZ are rarer than 1.85mm PTFE
* 10.9.18   Added 7mm ball bearing (you need this for the FINDA detector)
* 10.9.18   Added 5mm x 8mm coupler (need this for the selector stepper motor to threaded rod)

# BOM

## Prusa Parts
* MMU2 plastic parts - https://www.prusa3d.com/prusa-i3-printable-parts/

## Motors

* 3 Stepper Motors
  (DO NOT PURCHASE THESE MOTORS, THEY DO NOT HAVE SUFFICIENT STALL TORQUE)(https://www.amazon.com/gp/product/B0716S32G4/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1)
            (these motors are super cheap $10 per motor ... don't buy them because they don't have sufficient torque)
            (I used them for 3 weeks and chased problems that won't be there if you get better motors
            (get the motors I list below)
            
            
* 3   Stepper Motors 
  (PURCHASE THESE STEPPER MOTORS INSTEAD)(https://www.amazon.com/gp/product/B06XSYP24P/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)

  (these motors have 46 N-cm of stall torque.  They idler stepper motor needs quite a bit of stall torque to stay
            in place when the bearing is being moved against the extruder stepper motor).
            
  Get a motor with a minimum of 45 N-cm of stall torque (you will thank me later)
         
    These motors are nice and cheap - the problem with cheap is they are not 100% reliable. I am testing another brand at the 
    moment and when I have some decent test results I will report back.

## Other Stuff
* 5   mk8 hobbed gears (https://www.amazon.com/gp/product/B07CJPP7R7/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1)
* 2   100mm x 5mm steel shafts (https://www.amazon.com/gp/product/B01B27MJC6/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1)
     (these shafts are used to make your 16mm spindles for the bearings,  you can also order 16mm x 5mm spindles from McMcaster-Carr,
     (however, they are wicked tight on the bearings)
* 2   150mm x 5mm steel shafts (https://www.amazon.com/gp/product/B01B5QTM8I/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)
      (these shafts are used for the selector head shaft guides, you will have to cut them down to size)
      (if you don't know how to cut steel shafts then please stop and go do something else)
* 9   625-ZZ bearings (https://www.amazon.com/gp/product/B01CUTIQWW/ref=oh_aui_detailpage_o04_s01?ie=UTF8&psc=1)
* 20  3mm thin (1.8mm) square nuts) https://www.amazon.com/gp/product/B073SBCMBM/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1
* 1   5mm x 5mm coupler https://www.amazon.com/gp/product/B0159WO7T8/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1
                     (you need one but buy two because you can) 
* 1   5mm x 8mm coupler  (amazon.com ... too lazy to provide the link at the moment).
* 25' 4mm OD x 2mm ID PTFE Tubing (https://www.amazon.com/gp/product/B073RFQQ3Z/ref=oh_aui_detailpage_o09_s00?ie=UTF8&th=1)
                     Needed for the feeders from the spools to the MMU2 unit, you will learn to hate PTFE tubing
* 1   50mm 4mm OD x 1.85mm ID PTFE Tubing (flurostore.com has 1.80mm ID tubing - it works !!!)
                By far the most difficult part to obtain, it should just be called unobtanium
* 1   150mm x 8mm threaded shaft (https://www.amazon.com/gp/product/B07C8P1DWX/ref=oh_aui_detailpage_o08_s01?ie=UTF8&psc=1)
                (yes, you will have to cut it to size using some of your cool shop tools)
* 10  PC4-10 PTFE connectors (https://www.amazon.com/gp/product/B01IB81IHG/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1)
                (get these, they are awesome)
* 1   12-15V, 2A  Power supply - needed for the Arduino Mega/RAMPS board for initial testing
* 1   Arduino Mega 2560 (https://www.amazon.com/gp/product/B01H4ZDYCE/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)
* 1   1.x RAMPS Boards (https://www.amazon.com/gp/product/B0794YN8XK/ref=oh_aui_detailpage_o09_s00?ie=UTF8&psc=1)
                    (home for all of your stepper motor controllers)
* 3  8825 Stepper Motor Controller (https://www.amazon.com/gp/product/B00S3Q9YZA/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1)
                    (make certain to tweak the voltage rheostat on the top of this little wonder, goto polulu website)
                    (I currently have mine set to 0.60V - don't go too high you will fry this component)
* 1  Razor Blades (https://www.amazon.com/gp/product/B007QYAJRC/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1)
* 1  microswitch   (https://www.amazon.com/gp/product/B06XSBYQ8H/ref=oh_aui_detailpage_o05_s00?ie=UTF8&psc=1)
* 1  FINDA (aka PINDA) Probe (https://www.amazon.com/URBEST-Detecting-Distance-Inductive-Proximity/dp/B01M1777XK/ref=sr_1_fkmr1_3?s=industrial&ie=UTF8&qid=1538915473&sr=1-3-fkmr1&keywords=prusa+pinda+probe)
                  ( I had a spare probe laying around so I have NOT tried this inductive probe)
                  (they are also available from aliexpress.com)
* 1  7mm ball bearing  (mcmaster.carr or amazon), you only need one but you will have to buy many more

## Custom STL Files
* 1  MMU2 to PTFE Festo Coupler 
* 1  MK3 to PTFE Festo Coupler (w/ microswitch holder)
* 1  Selector Motor Mount offset block

## DigiKey Components (needed for cables and wiring)
(to be completed)

      

## Random Tools
(it's a project, you've got to buy new tools - you live for this stuff)
* 1 Reamer (https://www.amazon.com/gp/product/B01EIH573K/ref=oh_aui_detailpage_o07_s00?ie=UTF8&psc=1)
           (used to make awesome interior bevelled edges in that damn 2mm (and 1.80mm) PTFE
* 50mm cutting jig (https://www.thingiverse.com/thing:3062809)    
           (oh look, you get to make something with your 3d printer)

**Comment by KarlZeilhofer** [comment]
Keep up your great work!
Greets, Karl

**Comment by KarlZeilhofer** [comment]
PS: main purpose was to get clickable links for the lazy human :)

**Comment by cskozlowski** [comment]
Wow, that really looks fantastic.  How do I merge this back into the master?

**Comment by martinj** [comment]
@KarlZeilhofer maybe do a Pull Request for this?

**Comment by knoopx** [comment]
Click here: https://github.com/cskozlowski/mmu2/edit/master/README.md and paste the new readme :)

**Comment by KarlZeilhofer** [comment]
I didn't want to confuse him with a pullrequest. 

PPS: Until now I used Marp as a Markdown editor. But now I found Ghostwirter: This tool is awesome: https://wereturtle.github.io/ghostwriter/

If you are familiar with German, you can find some thoughts from me here: http://www.zeilhofer.co.at/wiki/doku.php?id=markdown#ghostwriter

**Comment by KarlZeilhofer** [comment]
@knoopx beware that I posted about the BOM, not the README.md

**Comment by KarlZeilhofer** [comment]
@cskozlowski I think you should have a look into Git, and how it is used. I can recommend you Gitkraken as a GUI client. http://gitkraken.com/

Then normal workflow for a Github project would be
* clone the repository with Gitkraken
* modify some files
* commit them to the repo (locally)
* 'push' them back to Github

Don't be afraid of the complexity of Git - Gitkraken takes most of the complexity into an intuitive interface.  
EDIT: normally you would not find something like firmware-v1.ino firmware-v2.ino firmware-v3.ino within one Git repo, because Git manages the versions for you :)

**Comment by KarlZeilhofer** [comment]
ok, i did a pullrequest now to bring this repo in a "standard" Github format: #2
